apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upf-gtpu-monitor
  namespace: free5gc
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: upf-metrics
  endpoints:
  - port: metrics
    interval: 10s
    path: /metrics
