apiVersion: v1
kind: Service
metadata:
  name: upf-metrics
  namespace: free5gc
  labels:
    app: upf-metrics
    nf: upf
spec:
  selector:
    nf: upf
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
